[package]
name = "gp_server"
version = "0.1.0"
edition = "2021"

[dependencies]
gp_scenario = { workspace = true }
axum = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
reqwest = { workspace = true }
tower-http = { workspace = true }
uuid = { version = "1.0", features = ["v4"] }
async-trait = "0.1"
