use crate::schema::{
    camel_case, pascal_case, ArrayRules, Contract, IntegerRules, ObjectSchema, Schema, StringRules,
};
use std::fmt::Write;

const PREFIX: &str = "GPV1";

pub(crate) fn emit(contract: &Contract) -> Result<String, String> {
    let named = contract.named_schemas()?;
    let mut output = String::new();
    writeln!(output, "// Generated by gp_contract_gen. Do not edit.").unwrap();
    writeln!(output, "// Canonical source: {}", contract.title).unwrap();
    output.push_str(KOTLIN_PRELUDE);

    for (name, schema) in named {
        render_named(contract, &name, &schema, &mut output)?;
    }
    Ok(output)
}

fn render_named(
    contract: &Contract,
    name: &str,
    schema: &Schema,
    output: &mut String,
) -> Result<(), String> {
    match contract.dereference(schema)? {
        Schema::String(rules) => render_string_wrapper(name, rules, output),
        Schema::StringConstant(value) => render_constant_wrapper(name, value, output),
        Schema::Integer(rules) => render_integer_wrapper(name, rules, output),
        Schema::Boolean => writeln!(output, "typealias {PREFIX}{name} = Boolean\n").unwrap(),
        Schema::Null => writeln!(output, "typealias {PREFIX}{name} = GPNull\n").unwrap(),
        Schema::Array(rules) => {
            let item = kotlin_type(contract, &rules.items, &format!("{name}Item"))?;
            writeln!(output, "typealias {PREFIX}{name} = List<{item}>\n").unwrap();
        }
        Schema::Object(_) | Schema::AllOf(_) => {
            render_object(contract, name, &contract.effective_object(schema)?, output)?;
        }
        Schema::OneOf(_) => render_union(contract, name, schema, output)?,
        Schema::Nullable(inner) => {
            let inner = kotlin_type(contract, inner, name)?;
            writeln!(output, "typealias {PREFIX}{name} = {inner}?\n").unwrap();
        }
        Schema::Reference(reference) => {
            writeln!(output, "typealias {PREFIX}{name} = {PREFIX}{reference}\n").unwrap();
        }
    }
    Ok(())
}

fn render_string_wrapper(name: &str, rules: &StringRules, output: &mut String) {
    writeln!(output, "data class {PREFIX}{name}(val value: String) {{").unwrap();
    output.push_str("    init {\n");
    render_string_validation("value", rules, "        ", output);
    output.push_str("    }\n\n");
    output.push_str("    companion object {\n");
    writeln!(
        output,
        "        fun from(json: GPJsonValue): {PREFIX}{name} {{"
    )
    .unwrap();
    writeln!(output, "            return {PREFIX}{name}(gpString(json))").unwrap();
    output.push_str("        }\n");
    output.push_str("    }\n\n");
    output.push_str("    fun toJson(): GPJsonValue = GPJsonValue.StringValue(value)\n");
    writeln!(
        output,
        "    override fun toString(): String = \"{PREFIX}{name}(<redacted>)\""
    )
    .unwrap();
    output.push_str("}\n\n");
}

fn render_constant_wrapper(name: &str, value: &str, output: &mut String) {
    writeln!(output, "data class {PREFIX}{name}(val value: String) {{").unwrap();
    output.push_str("    init {\n");
    writeln!(
        output,
        "        gpRequire(value == {}, \"expected constant {name}\")",
        quoted_kotlin(value)
    )
    .unwrap();
    output.push_str("    }\n\n");
    output.push_str("    companion object {\n");
    writeln!(
        output,
        "        fun from(json: GPJsonValue): {PREFIX}{name} {{"
    )
    .unwrap();
    writeln!(output, "            return {PREFIX}{name}(gpString(json))").unwrap();
    output.push_str("        }\n");
    output.push_str("    }\n\n");
    output.push_str("    fun toJson(): GPJsonValue = GPJsonValue.StringValue(value)\n");
    writeln!(
        output,
        "    override fun toString(): String = \"{PREFIX}{name}(<redacted>)\""
    )
    .unwrap();
    output.push_str("}\n\n");
}

fn render_integer_wrapper(name: &str, rules: &IntegerRules, output: &mut String) {
    writeln!(output, "data class {PREFIX}{name}(val value: Long) {{").unwrap();
    output.push_str("    init {\n");
    render_integer_validation("value", rules, "        ", output);
    output.push_str("    }\n\n");
    output.push_str("    companion object {\n");
    writeln!(
        output,
        "        fun from(json: GPJsonValue): {PREFIX}{name} {{"
    )
    .unwrap();
    writeln!(output, "            return {PREFIX}{name}(gpInteger(json))").unwrap();
    output.push_str("        }\n");
    output.push_str("    }\n\n");
    output.push_str("    fun toJson(): GPJsonValue = GPJsonValue.IntegerValue(value)\n");
    writeln!(
        output,
        "    override fun toString(): String = \"{PREFIX}{name}(<redacted>)\""
    )
    .unwrap();
    output.push_str("}\n\n");
}

fn render_object(
    contract: &Contract,
    name: &str,
    object: &ObjectSchema,
    output: &mut String,
) -> Result<(), String> {
    if object.properties.is_empty() {
        writeln!(output, "data object {PREFIX}{name} {{").unwrap();
        writeln!(output, "    fun from(json: GPJsonValue): {PREFIX}{name} {{").unwrap();
        output.push_str("        gpObject(json)\n");
        output.push_str("        return this\n");
        output.push_str("    }\n\n");
        output.push_str("    fun toJson(): GPJsonValue = GPJsonValue.ObjectValue(emptyMap())\n");
        output.push_str("}\n\n");
        return Ok(());
    }
    writeln!(output, "data class {PREFIX}{name}(").unwrap();
    let properties: Vec<_> = object.properties.iter().collect();
    for (index, (property_name, schema)) in properties.iter().enumerate() {
        let hint = format!("{name}{}", pascal_case(property_name));
        let mut property_type = kotlin_type(contract, schema, &hint)?;
        if !object.required.contains(*property_name) && !property_type.ends_with('?') {
            property_type.push('?');
        }
        let comma = if index + 1 == properties.len() {
            ""
        } else {
            ","
        };
        writeln!(
            output,
            "    val {}: {property_type}{comma}",
            camel_case(property_name)
        )
        .unwrap();
    }
    output.push_str(") {\n");
    output.push_str("    init {\n");
    for (property_name, schema) in &object.properties {
        let variable = camel_case(property_name);
        if object.required.contains(property_name) {
            render_validation(contract, schema, &variable, "        ", output)?;
        } else {
            render_optional_validation(contract, schema, &variable, "        ", output)?;
        }
    }
    output.push_str("    }\n\n");
    output.push_str("    companion object {\n");
    writeln!(
        output,
        "        fun from(json: GPJsonValue): {PREFIX}{name} {{"
    )
    .unwrap();
    output.push_str("            val members = gpObject(json)\n");
    for (property_name, schema) in &object.properties {
        render_decode_property(contract, name, property_name, schema, object, output)?;
    }
    writeln!(output, "            return {PREFIX}{name}(").unwrap();
    for (index, property_name) in object.properties.keys().enumerate() {
        let comma = if index + 1 == object.properties.len() {
            ""
        } else {
            ","
        };
        let variable = camel_case(property_name);
        writeln!(output, "                {variable} = {variable}{comma}").unwrap();
    }
    output.push_str("            )\n");
    output.push_str("        }\n");
    output.push_str("    }\n\n");

    output.push_str("    fun toJson(): GPJsonValue {\n");
    output.push_str("        val members = linkedMapOf<String, GPJsonValue>()\n");
    for (property_name, schema) in &object.properties {
        render_encode_property(name, property_name, schema, object, output)?;
    }
    output.push_str("        return GPJsonValue.ObjectValue(members)\n");
    output.push_str("    }\n");
    writeln!(
        output,
        "\n    override fun toString(): String = \"{PREFIX}{name}(<redacted>)\""
    )
    .unwrap();
    output.push_str("}\n\n");
    Ok(())
}

fn render_decode_property(
    contract: &Contract,
    parent_name: &str,
    property_name: &str,
    schema: &Schema,
    object: &ObjectSchema,
    output: &mut String,
) -> Result<(), String> {
    let variable = camel_case(property_name);
    let hint = format!("{parent_name}{}", pascal_case(property_name));
    let required = object.required.contains(property_name);
    let mut property_type = kotlin_type(contract, schema, &hint)?;
    if !required && !property_type.ends_with('?') {
        property_type.push('?');
    }
    match schema {
        Schema::Nullable(inner) => {
            let parse = kotlin_parse_expression(inner, &hint, "raw")?;
            if required {
                writeln!(output, "            val {variable}: {property_type} = when (val raw = gpRequired(members, {})) {{", quoted_kotlin(property_name)).unwrap();
                output.push_str("                GPJsonValue.NullValue -> null\n");
                writeln!(output, "                else -> {parse}").unwrap();
                output.push_str("            }\n");
            } else {
                writeln!(
                    output,
                    "            val {variable}: {property_type} = members[{}]?.let {{ raw ->",
                    quoted_kotlin(property_name)
                )
                .unwrap();
                output.push_str("                if (raw == GPJsonValue.NullValue) null else ");
                writeln!(output, "{parse}").unwrap();
                output.push_str("            }\n");
            }
            render_optional_validation(contract, inner, &variable, "            ", output)?;
        }
        Schema::Null => {
            if required {
                writeln!(
                    output,
                    "            val {variable}: GPNull = gpNull(gpRequired(members, {}))",
                    quoted_kotlin(property_name)
                )
                .unwrap();
            } else {
                writeln!(
                    output,
                    "            val {variable}: GPNull? = members[{}]?.let(::gpNull)",
                    quoted_kotlin(property_name)
                )
                .unwrap();
            }
        }
        _ => {
            let source = if required {
                format!("gpRequired(members, {})", quoted_kotlin(property_name))
            } else {
                "raw".to_string()
            };
            let parse = kotlin_parse_expression(schema, &hint, &source)?;
            if required {
                writeln!(
                    output,
                    "            val {variable}: {property_type} = {parse}"
                )
                .unwrap();
                render_validation(contract, schema, &variable, "            ", output)?;
            } else {
                writeln!(output, "            val {variable}: {property_type} = members[{}]?.let {{ raw -> {parse} }}", quoted_kotlin(property_name)).unwrap();
                render_optional_validation(contract, schema, &variable, "            ", output)?;
            }
        }
    }
    Ok(())
}

fn render_encode_property(
    parent_name: &str,
    property_name: &str,
    schema: &Schema,
    object: &ObjectSchema,
    output: &mut String,
) -> Result<(), String> {
    let variable = camel_case(property_name);
    let hint = format!("{parent_name}{}", pascal_case(property_name));
    let required = object.required.contains(property_name);
    match schema {
        Schema::Nullable(inner) if required => {
            let expression = kotlin_to_json_expression(inner, &hint, "value")?;
            writeln!(output, "        members[{}] = {variable}?.let {{ value -> {expression} }} ?: GPJsonValue.NullValue", quoted_kotlin(property_name)).unwrap();
        }
        Schema::Null if required => {
            writeln!(
                output,
                "        members[{}] = GPJsonValue.NullValue",
                quoted_kotlin(property_name)
            )
            .unwrap();
        }
        Schema::Null => {
            writeln!(
                output,
                "        if ({variable} != null) members[{}] = GPJsonValue.NullValue",
                quoted_kotlin(property_name)
            )
            .unwrap();
        }
        _ if required => {
            let expression = kotlin_to_json_expression(schema, &hint, &variable)?;
            writeln!(
                output,
                "        members[{}] = {expression}",
                quoted_kotlin(property_name)
            )
            .unwrap();
        }
        _ => {
            let expression = kotlin_to_json_expression(schema, &hint, "value")?;
            writeln!(
                output,
                "        {variable}?.let {{ value -> members[{}] = {expression} }}",
                quoted_kotlin(property_name)
            )
            .unwrap();
        }
    }
    Ok(())
}

fn render_union(
    contract: &Contract,
    name: &str,
    schema: &Schema,
    output: &mut String,
) -> Result<(), String> {
    let (discriminator, variants) = contract.discriminated_variants(schema, name)?;
    writeln!(output, "sealed interface {PREFIX}{name} {{").unwrap();
    output.push_str("    fun toJson(): GPJsonValue\n\n");
    for variant in &variants {
        let case_name = pascal_case(&variant.literal);
        writeln!(
            output,
            "    data class {case_name}(val value: {PREFIX}{}) : {PREFIX}{name} {{",
            variant.type_name
        )
        .unwrap();
        output.push_str("        override fun toJson(): GPJsonValue = value.toJson()\n");
        writeln!(
            output,
            "        override fun toString(): String = \"{PREFIX}{name}.{case_name}(<redacted>)\""
        )
        .unwrap();
        output.push_str("    }\n\n");
    }
    output.push_str("    companion object {\n");
    writeln!(
        output,
        "        fun from(json: GPJsonValue): {PREFIX}{name} {{"
    )
    .unwrap();
    output.push_str("            val members = gpObject(json)\n");
    writeln!(
        output,
        "            return when (gpString(gpRequired(members, {}))) {{",
        quoted_kotlin(&discriminator)
    )
    .unwrap();
    for variant in &variants {
        writeln!(
            output,
            "                {} -> {}({PREFIX}{}.from(json))",
            quoted_kotlin(&variant.literal),
            pascal_case(&variant.literal),
            variant.type_name
        )
        .unwrap();
    }
    writeln!(
        output,
        "                else -> throw GPContractException(\"unsupported variant for {}\")",
        discriminator
    )
    .unwrap();
    output.push_str("            }\n");
    output.push_str("        }\n");
    output.push_str("    }\n");
    output.push_str("}\n\n");
    Ok(())
}

fn kotlin_type(contract: &Contract, schema: &Schema, hint: &str) -> Result<String, String> {
    match schema {
        Schema::Reference(name) => Ok(format!("{PREFIX}{name}")),
        Schema::String(_) | Schema::StringConstant(_) => Ok("String".to_string()),
        Schema::Integer(_) => Ok("Long".to_string()),
        Schema::Boolean => Ok("Boolean".to_string()),
        Schema::Null => Ok("GPNull".to_string()),
        Schema::Array(rules) => Ok(format!(
            "List<{}>",
            kotlin_type(contract, &rules.items, &format!("{hint}Item"))?
        )),
        Schema::Nullable(inner) => Ok(format!("{}?", kotlin_type(contract, inner, hint)?)),
        Schema::Object(_) | Schema::OneOf(_) | Schema::AllOf(_) => {
            let _ = contract;
            Ok(format!("{PREFIX}{hint}"))
        }
    }
}

fn kotlin_parse_expression(schema: &Schema, hint: &str, source: &str) -> Result<String, String> {
    match schema {
        Schema::Reference(name) => Ok(format!("{PREFIX}{name}.from({source})")),
        Schema::String(_) | Schema::StringConstant(_) => Ok(format!("gpString({source})")),
        Schema::Integer(_) => Ok(format!("gpInteger({source})")),
        Schema::Boolean => Ok(format!("gpBoolean({source})")),
        Schema::Null => Ok(format!("gpNull({source})")),
        Schema::Array(rules) => {
            let item = kotlin_parse_expression(&rules.items, &format!("{hint}Item"), "item")?;
            Ok(format!("gpArray({source}).map {{ item -> {item} }}"))
        }
        Schema::Nullable(inner) => {
            let inner = kotlin_parse_expression(inner, hint, source)?;
            Ok(format!(
                "if ({source} == GPJsonValue.NullValue) null else {inner}"
            ))
        }
        Schema::Object(_) | Schema::OneOf(_) | Schema::AllOf(_) => {
            Ok(format!("{PREFIX}{hint}.from({source})"))
        }
    }
}

fn kotlin_to_json_expression(schema: &Schema, hint: &str, source: &str) -> Result<String, String> {
    match schema {
        Schema::Reference(_) | Schema::Object(_) | Schema::OneOf(_) | Schema::AllOf(_) => {
            Ok(format!("{source}.toJson()"))
        }
        Schema::String(_) | Schema::StringConstant(_) => {
            Ok(format!("GPJsonValue.StringValue({source})"))
        }
        Schema::Integer(_) => Ok(format!("GPJsonValue.IntegerValue({source})")),
        Schema::Boolean => Ok(format!("GPJsonValue.BooleanValue({source})")),
        Schema::Null => Ok("GPJsonValue.NullValue".to_string()),
        Schema::Array(rules) => {
            let item = kotlin_to_json_expression(&rules.items, &format!("{hint}Item"), "item")?;
            Ok(format!(
                "GPJsonValue.ArrayValue({source}.map {{ item -> {item} }})"
            ))
        }
        Schema::Nullable(inner) => {
            let inner = kotlin_to_json_expression(inner, hint, "value")?;
            Ok(format!(
                "{source}?.let {{ value -> {inner} }} ?: GPJsonValue.NullValue"
            ))
        }
    }
}

fn render_optional_validation(
    contract: &Contract,
    schema: &Schema,
    variable: &str,
    indent: &str,
    output: &mut String,
) -> Result<(), String> {
    if needs_inline_validation(schema) {
        writeln!(output, "{indent}{variable}?.let {{ value ->").unwrap();
        render_validation(contract, schema, "value", &format!("{indent}    "), output)?;
        writeln!(output, "{indent}}}").unwrap();
    }
    Ok(())
}

fn render_validation(
    contract: &Contract,
    schema: &Schema,
    expression: &str,
    indent: &str,
    output: &mut String,
) -> Result<(), String> {
    match schema {
        Schema::Reference(_) | Schema::Object(_) | Schema::OneOf(_) | Schema::AllOf(_) => {}
        Schema::String(rules) => render_string_validation(expression, rules, indent, output),
        Schema::StringConstant(value) => writeln!(
            output,
            "{indent}gpRequire({expression} == {}, \"unexpected constant for {expression}\")",
            quoted_kotlin(value)
        )
        .unwrap(),
        Schema::Integer(rules) => render_integer_validation(expression, rules, indent, output),
        Schema::Boolean | Schema::Null => {}
        Schema::Nullable(inner) if needs_inline_validation(inner) => {
            writeln!(output, "{indent}{expression}?.let {{ value ->").unwrap();
            render_validation(contract, inner, "value", &format!("{indent}    "), output)?;
            writeln!(output, "{indent}}}").unwrap();
        }
        Schema::Nullable(_) => {}
        Schema::Array(rules) => {
            render_array_validation(contract, expression, rules, indent, output)?
        }
    }
    Ok(())
}

fn render_string_validation(
    expression: &str,
    rules: &StringRules,
    indent: &str,
    output: &mut String,
) {
    if let Some(minimum) = rules.minimum_length {
        writeln!(output, "{indent}gpRequire({expression}.codePointCount(0, {expression}.length).toULong() >= {minimum}uL, \"string is shorter than minLength\")").unwrap();
    }
    if let Some(maximum) = rules.maximum_length {
        writeln!(output, "{indent}gpRequire({expression}.codePointCount(0, {expression}.length).toULong() <= {maximum}uL, \"string is longer than maxLength\")").unwrap();
    }
    if let Some(pattern) = &rules.pattern {
        writeln!(output, "{indent}gpRequire(Regex({}).containsMatchIn({expression}), \"string does not match pattern\")", quoted_kotlin(pattern)).unwrap();
    }
}

fn render_integer_validation(
    expression: &str,
    rules: &IntegerRules,
    indent: &str,
    output: &mut String,
) {
    if let Some(minimum) = rules.minimum {
        writeln!(
            output,
            "{indent}gpRequire({expression} >= {minimum}L, \"integer is below minimum\")"
        )
        .unwrap();
    }
    if let Some(maximum) = rules.maximum {
        writeln!(
            output,
            "{indent}gpRequire({expression} <= {maximum}L, \"integer is above maximum\")"
        )
        .unwrap();
    }
}

fn render_array_validation(
    contract: &Contract,
    expression: &str,
    rules: &ArrayRules,
    indent: &str,
    output: &mut String,
) -> Result<(), String> {
    if let Some(minimum) = rules.minimum_items {
        writeln!(
            output,
            "{indent}gpRequire({expression}.size >= {minimum}, \"array is shorter than minItems\")"
        )
        .unwrap();
    }
    if let Some(maximum) = rules.maximum_items {
        writeln!(
            output,
            "{indent}gpRequire({expression}.size <= {maximum}, \"array is longer than maxItems\")"
        )
        .unwrap();
    }
    if rules.unique_items {
        writeln!(output, "{indent}gpRequire({expression}.toSet().size == {expression}.size, \"array items are not unique\")").unwrap();
    }
    if needs_inline_validation(&rules.items) {
        writeln!(output, "{indent}{expression}.forEach {{ item ->").unwrap();
        render_validation(
            contract,
            &rules.items,
            "item",
            &format!("{indent}    "),
            output,
        )?;
        writeln!(output, "{indent}}}").unwrap();
    }
    Ok(())
}

fn needs_inline_validation(schema: &Schema) -> bool {
    match schema {
        Schema::String(rules) => {
            rules.minimum_length.is_some()
                || rules.maximum_length.is_some()
                || rules.pattern.is_some()
        }
        Schema::StringConstant(_) => true,
        Schema::Integer(rules) => rules.minimum.is_some() || rules.maximum.is_some(),
        Schema::Array(rules) => {
            rules.minimum_items.is_some()
                || rules.maximum_items.is_some()
                || rules.unique_items
                || needs_inline_validation(&rules.items)
        }
        Schema::Nullable(inner) => needs_inline_validation(inner),
        _ => false,
    }
}

fn quoted_kotlin(value: &str) -> String {
    serde_json::to_string(value)
        .expect("serializing a string cannot fail")
        .replace('$', "\\$")
}

const KOTLIN_PRELUDE: &str = r#"
package guiltyparty.contracts.v1

sealed interface GPJsonValue {
    data object NullValue : GPJsonValue
    data class BooleanValue(val value: Boolean) : GPJsonValue {
        override fun toString(): String = "GPJsonValue.BooleanValue(<redacted>)"
    }
    data class IntegerValue(val value: Long) : GPJsonValue {
        override fun toString(): String = "GPJsonValue.IntegerValue(<redacted>)"
    }
    data class StringValue(val value: String) : GPJsonValue {
        override fun toString(): String = "GPJsonValue.StringValue(<redacted>)"
    }
    data class ArrayValue(val values: List<GPJsonValue>) : GPJsonValue {
        override fun toString(): String = "GPJsonValue.ArrayValue(<redacted>)"
    }
    data class ObjectValue(val members: Map<String, GPJsonValue>) : GPJsonValue {
        override fun toString(): String = "GPJsonValue.ObjectValue(<redacted>)"
    }
}

data object GPNull

class GPContractException(message: String) : IllegalArgumentException(message)

internal fun gpRequire(condition: Boolean, message: String) {
    if (!condition) throw GPContractException(message)
}

internal fun gpRequired(members: Map<String, GPJsonValue>, name: String): GPJsonValue =
    members[name] ?: throw GPContractException("missing required member $name")

internal fun gpObject(value: GPJsonValue): Map<String, GPJsonValue> =
    (value as? GPJsonValue.ObjectValue)?.members
        ?: throw GPContractException("expected object")

internal fun gpArray(value: GPJsonValue): List<GPJsonValue> =
    (value as? GPJsonValue.ArrayValue)?.values
        ?: throw GPContractException("expected array")

internal fun gpString(value: GPJsonValue): String =
    (value as? GPJsonValue.StringValue)?.value
        ?: throw GPContractException("expected string")

internal fun gpInteger(value: GPJsonValue): Long =
    (value as? GPJsonValue.IntegerValue)?.value
        ?: throw GPContractException("expected integer")

internal fun gpBoolean(value: GPJsonValue): Boolean =
    (value as? GPJsonValue.BooleanValue)?.value
        ?: throw GPContractException("expected boolean")

internal fun gpNull(value: GPJsonValue): GPNull {
    if (value != GPJsonValue.NullValue) throw GPContractException("expected null")
    return GPNull
}

"#;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn kotlin_literals_escape_interpolation_markers() {
        assert_eq!(quoted_kotlin("${42}"), "\"\\${42}\"");
        assert_eq!(quoted_kotlin("$value"), "\"\\$value\"");
    }

    #[test]
    fn max_items_alone_requires_inline_validation() {
        let schema = Schema::Nullable(Box::new(Schema::Array(ArrayRules {
            items: Box::new(Schema::String(StringRules::default())),
            minimum_items: None,
            maximum_items: Some(3),
            unique_items: false,
        })));
        assert!(needs_inline_validation(&schema));
    }
}
