use crate::schema::{
    camel_case, pascal_case, ArrayRules, Contract, IntegerRules, ObjectSchema, Schema, StringRules,
};
use std::fmt::Write;

const PREFIX: &str = "GPV1";

pub(crate) fn emit(contract: &Contract) -> Result<String, String> {
    let named = contract.named_schemas()?;
    let mut output = String::new();
    writeln!(output, "// Generated by gp_contract_gen. Do not edit.").unwrap();
    writeln!(output, "// Canonical source: {}", contract.title).unwrap();
    output.push_str(SWIFT_PRELUDE);

    for (name, schema) in named {
        render_named(contract, &name, &schema, &mut output)?;
    }
    Ok(output)
}

fn render_named(
    contract: &Contract,
    name: &str,
    schema: &Schema,
    output: &mut String,
) -> Result<(), String> {
    match contract.dereference(schema)? {
        Schema::String(rules) => render_string_wrapper(name, rules, output),
        Schema::StringConstant(value) => render_constant_wrapper(name, value, output),
        Schema::Integer(rules) => render_integer_wrapper(name, rules, output),
        Schema::Boolean => {
            writeln!(output, "public typealias {PREFIX}{name} = Bool\n").unwrap();
        }
        Schema::Null => {
            writeln!(output, "public typealias {PREFIX}{name} = GPNull\n").unwrap();
        }
        Schema::Array(rules) => {
            let item = swift_type(contract, &rules.items, &format!("{name}Item"))?;
            writeln!(output, "public typealias {PREFIX}{name} = [{item}]\n").unwrap();
        }
        Schema::Object(_) | Schema::AllOf(_) => {
            let object = contract.effective_object(schema)?;
            render_object(contract, name, &object, output)?;
        }
        Schema::OneOf(_) => render_union(contract, name, schema, output)?,
        Schema::Nullable(inner) => {
            let inner = swift_type(contract, inner, name)?;
            writeln!(output, "public typealias {PREFIX}{name} = {inner}?\n").unwrap();
        }
        Schema::Reference(reference) => {
            writeln!(
                output,
                "public typealias {PREFIX}{name} = {PREFIX}{reference}\n"
            )
            .unwrap();
        }
    }
    Ok(())
}

fn render_string_wrapper(name: &str, rules: &StringRules, output: &mut String) {
    writeln!(
        output,
        "public struct {PREFIX}{name}: Codable, Equatable, Hashable, Sendable {{"
    )
    .unwrap();
    output.push_str("    public let value: String\n\n");
    output.push_str("    public init(_ value: String) throws {\n");
    output.push_str("        self.value = value\n");
    render_string_validation("value", rules, "        ", output);
    output.push_str("    }\n\n");
    output.push_str("    public init(from decoder: Decoder) throws {\n");
    output.push_str("        let container = try decoder.singleValueContainer()\n");
    output.push_str("        value = try container.decode(String.self)\n");
    render_string_validation("value", rules, "        ", output);
    output.push_str("    }\n\n");
    output.push_str("    public func encode(to encoder: Encoder) throws {\n");
    output.push_str("        var container = encoder.singleValueContainer()\n");
    output.push_str("        try container.encode(value)\n");
    output.push_str("    }\n");
    output.push_str("}\n\n");
}

fn render_constant_wrapper(name: &str, value: &str, output: &mut String) {
    let value = quoted(value);
    writeln!(
        output,
        "public struct {PREFIX}{name}: Codable, Equatable, Hashable, Sendable {{"
    )
    .unwrap();
    output.push_str("    public let value: String\n\n");
    output.push_str("    public init() {\n");
    writeln!(output, "        value = {value}").unwrap();
    output.push_str("    }\n\n");
    output.push_str("    public init(from decoder: Decoder) throws {\n");
    output.push_str("        let container = try decoder.singleValueContainer()\n");
    output.push_str("        value = try container.decode(String.self)\n");
    writeln!(
        output,
        "        guard value == {value} else {{ throw GPContractError.constraint(\"expected constant {name}\") }}"
    )
    .unwrap();
    output.push_str("    }\n\n");
    output.push_str("    public func encode(to encoder: Encoder) throws {\n");
    output.push_str("        var container = encoder.singleValueContainer()\n");
    output.push_str("        try container.encode(value)\n");
    output.push_str("    }\n");
    output.push_str("}\n\n");
}

fn render_integer_wrapper(name: &str, rules: &IntegerRules, output: &mut String) {
    writeln!(
        output,
        "public struct {PREFIX}{name}: Codable, Equatable, Hashable, Sendable {{"
    )
    .unwrap();
    output.push_str("    public let value: Int64\n\n");
    output.push_str("    public init(_ value: Int64) throws {\n");
    output.push_str("        self.value = value\n");
    render_integer_validation("value", rules, "        ", output);
    output.push_str("    }\n\n");
    output.push_str("    public init(from decoder: Decoder) throws {\n");
    output.push_str("        let container = try decoder.singleValueContainer()\n");
    output.push_str("        value = try container.decode(Int64.self)\n");
    render_integer_validation("value", rules, "        ", output);
    output.push_str("    }\n\n");
    output.push_str("    public func encode(to encoder: Encoder) throws {\n");
    output.push_str("        var container = encoder.singleValueContainer()\n");
    output.push_str("        try container.encode(value)\n");
    output.push_str("    }\n");
    output.push_str("}\n\n");
}

fn render_object(
    contract: &Contract,
    name: &str,
    object: &ObjectSchema,
    output: &mut String,
) -> Result<(), String> {
    writeln!(
        output,
        "public struct {PREFIX}{name}: Codable, Equatable, Sendable {{"
    )
    .unwrap();
    for (property_name, schema) in &object.properties {
        let variable = camel_case(property_name);
        let hint = format!("{name}{}", pascal_case(property_name));
        let mut property_type = swift_type(contract, schema, &hint)?;
        if !object.required.contains(property_name) && !property_type.ends_with('?') {
            property_type.push('?');
        }
        writeln!(output, "    public let {variable}: {property_type}").unwrap();
    }
    if !object.properties.is_empty() {
        output.push('\n');
    }

    if object.properties.is_empty() {
        output.push_str("    public init() {}\n\n");
    } else {
        output.push_str("    public init(\n");
        let properties: Vec<_> = object.properties.iter().collect();
        for (index, (property_name, schema)) in properties.iter().enumerate() {
            let variable = camel_case(property_name);
            let hint = format!("{name}{}", pascal_case(property_name));
            let required = object.required.contains(*property_name);
            let mut property_type = swift_type(contract, schema, &hint)?;
            if !required && !property_type.ends_with('?') {
                property_type.push('?');
            }
            let default = if required { "" } else { " = nil" };
            let comma = if index + 1 == properties.len() {
                ""
            } else {
                ","
            };
            writeln!(
                output,
                "        {variable}: {property_type}{default}{comma}"
            )
            .unwrap();
        }
        output.push_str("    ) throws {\n");
        for property_name in object.properties.keys() {
            let variable = camel_case(property_name);
            writeln!(output, "        self.{variable} = {variable}").unwrap();
        }
        for (property_name, schema) in &object.properties {
            let variable = camel_case(property_name);
            if object.required.contains(property_name) {
                render_validation(contract, schema, &variable, "        ", output)?;
            } else if needs_inline_validation(schema) {
                writeln!(output, "        if let value = {variable} {{").unwrap();
                render_validation(contract, schema, "value", "            ", output)?;
                output.push_str("        }\n");
            }
        }
        output.push_str("    }\n\n");
    }

    if !object.properties.is_empty() {
        output.push_str("    private enum CodingKeys: String, CodingKey {\n");
        for property_name in object.properties.keys() {
            writeln!(
                output,
                "        case {} = {}",
                camel_case(property_name),
                quoted(property_name)
            )
            .unwrap();
        }
        output.push_str("    }\n\n");
    }

    output.push_str("    public init(from decoder: Decoder) throws {\n");
    if object.properties.is_empty() {
        output.push_str("        _ = try decoder.container(keyedBy: GPDynamicCodingKey.self)\n");
    } else {
        output
            .push_str("        let container = try decoder.container(keyedBy: CodingKeys.self)\n");
        for (property_name, schema) in &object.properties {
            render_decode_property(contract, name, property_name, schema, object, output)?;
        }
    }
    output.push_str("    }\n\n");

    output.push_str("    public func encode(to encoder: Encoder) throws {\n");
    if object.properties.is_empty() {
        output.push_str("        _ = encoder.container(keyedBy: GPDynamicCodingKey.self)\n");
    } else {
        output.push_str("        var container = encoder.container(keyedBy: CodingKeys.self)\n");
        for (property_name, schema) in &object.properties {
            render_encode_property(property_name, schema, object, output);
        }
    }
    output.push_str("    }\n");
    output.push_str("}\n\n");
    Ok(())
}

fn render_decode_property(
    contract: &Contract,
    parent_name: &str,
    property_name: &str,
    schema: &Schema,
    object: &ObjectSchema,
    output: &mut String,
) -> Result<(), String> {
    let variable = camel_case(property_name);
    let hint = format!("{parent_name}{}", pascal_case(property_name));
    let required = object.required.contains(property_name);
    match schema {
        Schema::Nullable(inner) => {
            if required {
                writeln!(
                    output,
                    "        guard container.contains(.{variable}) else {{ throw DecodingError.keyNotFound(CodingKeys.{variable}, .init(codingPath: decoder.codingPath, debugDescription: \"missing required nullable member {property_name}\")) }}"
                )
                .unwrap();
                let inner_type = swift_type(contract, inner, &hint)?;
                writeln!(
                    output,
                    "        {variable} = try container.decodeIfPresent({inner_type}.self, forKey: .{variable})"
                )
                .unwrap();
            } else {
                let inner_type = swift_type(contract, inner, &hint)?;
                writeln!(
                    output,
                    "        {variable} = try container.decodeIfPresent({inner_type}.self, forKey: .{variable})"
                )
                .unwrap();
            }
        }
        Schema::Null => {
            writeln!(output, "        if container.contains(.{variable}) {{").unwrap();
            writeln!(
                output,
                "            guard try container.decodeNil(forKey: .{variable}) else {{ throw GPContractError.constraint(\"{property_name} must be null\") }}"
            )
            .unwrap();
            writeln!(output, "            {variable} = GPNull()").unwrap();
            output.push_str("        } else {\n");
            if required {
                writeln!(
                    output,
                    "            throw DecodingError.keyNotFound(CodingKeys.{variable}, .init(codingPath: decoder.codingPath, debugDescription: \"missing required null member {property_name}\"))"
                )
                .unwrap();
            } else {
                writeln!(output, "            {variable} = nil").unwrap();
            }
            output.push_str("        }\n");
        }
        _ => {
            let property_type = swift_type(contract, schema, &hint)?;
            if required {
                writeln!(
                    output,
                    "        {variable} = try container.decode({property_type}.self, forKey: .{variable})"
                )
                .unwrap();
                render_validation(contract, schema, &variable, "        ", output)?;
            } else {
                writeln!(output, "        if container.contains(.{variable}) {{").unwrap();
                writeln!(
                    output,
                    "            let decoded = try container.decode({property_type}.self, forKey: .{variable})"
                )
                .unwrap();
                render_validation(contract, schema, "decoded", "            ", output)?;
                writeln!(output, "            {variable} = decoded").unwrap();
                output.push_str("        } else {\n");
                writeln!(output, "            {variable} = nil").unwrap();
                output.push_str("        }\n");
            }
        }
    }
    Ok(())
}

fn render_encode_property(
    property_name: &str,
    schema: &Schema,
    object: &ObjectSchema,
    output: &mut String,
) {
    let variable = camel_case(property_name);
    let required = object.required.contains(property_name);
    match schema {
        Schema::Nullable(_) if required => {
            writeln!(output, "        if let value = {variable} {{").unwrap();
            writeln!(
                output,
                "            try container.encode(value, forKey: .{variable})"
            )
            .unwrap();
            output.push_str("        } else {\n");
            writeln!(
                output,
                "            try container.encodeNil(forKey: .{variable})"
            )
            .unwrap();
            output.push_str("        }\n");
        }
        Schema::Null => {
            if required {
                writeln!(
                    output,
                    "        try container.encodeNil(forKey: .{variable})"
                )
                .unwrap();
            } else {
                writeln!(output, "        if {variable} != nil {{ try container.encodeNil(forKey: .{variable}) }}").unwrap();
            }
        }
        _ if required => {
            writeln!(
                output,
                "        try container.encode({variable}, forKey: .{variable})"
            )
            .unwrap();
        }
        _ => {
            writeln!(
                output,
                "        try container.encodeIfPresent({variable}, forKey: .{variable})"
            )
            .unwrap();
        }
    }
}

fn render_union(
    contract: &Contract,
    name: &str,
    schema: &Schema,
    output: &mut String,
) -> Result<(), String> {
    let (discriminator, variants) = contract.discriminated_variants(schema, name)?;
    writeln!(
        output,
        "public enum {PREFIX}{name}: Codable, Equatable, Sendable {{"
    )
    .unwrap();
    for variant in &variants {
        writeln!(
            output,
            "    case {}({PREFIX}{})",
            camel_case(&variant.literal),
            variant.type_name
        )
        .unwrap();
    }
    output.push_str("\n    private enum DiscriminatorKeys: String, CodingKey {\n");
    writeln!(
        output,
        "        case discriminator = {}",
        quoted(&discriminator)
    )
    .unwrap();
    output.push_str("    }\n\n");
    output.push_str("    public init(from decoder: Decoder) throws {\n");
    output.push_str(
        "        let container = try decoder.container(keyedBy: DiscriminatorKeys.self)\n",
    );
    output.push_str(
        "        let discriminator = try container.decode(String.self, forKey: .discriminator)\n",
    );
    output.push_str("        switch discriminator {\n");
    for variant in &variants {
        writeln!(output, "        case {}:", quoted(&variant.literal)).unwrap();
        writeln!(
            output,
            "            self = .{}(try {PREFIX}{}.init(from: decoder))",
            camel_case(&variant.literal),
            variant.type_name
        )
        .unwrap();
    }
    output.push_str("        default:\n");
    writeln!(
        output,
        "            throw GPContractError.unsupportedVariant(field: {}, value: discriminator)",
        quoted(&discriminator)
    )
    .unwrap();
    output.push_str("        }\n");
    output.push_str("    }\n\n");
    output.push_str("    public func encode(to encoder: Encoder) throws {\n");
    output.push_str("        switch self {\n");
    for variant in &variants {
        writeln!(
            output,
            "        case .{}(let value): try value.encode(to: encoder)",
            camel_case(&variant.literal)
        )
        .unwrap();
    }
    output.push_str("        }\n");
    output.push_str("    }\n");
    output.push_str("}\n\n");
    Ok(())
}

fn swift_type(contract: &Contract, schema: &Schema, hint: &str) -> Result<String, String> {
    match schema {
        Schema::Reference(name) => Ok(format!("{PREFIX}{name}")),
        Schema::String(_) | Schema::StringConstant(_) => Ok("String".to_string()),
        Schema::Integer(_) => Ok("Int64".to_string()),
        Schema::Boolean => Ok("Bool".to_string()),
        Schema::Null => Ok("GPNull".to_string()),
        Schema::Array(rules) => Ok(format!(
            "[{}]",
            swift_type(contract, &rules.items, &format!("{hint}Item"))?
        )),
        Schema::Nullable(inner) => Ok(format!("{}?", swift_type(contract, inner, hint)?)),
        Schema::Object(_) | Schema::OneOf(_) | Schema::AllOf(_) => {
            let _ = contract;
            Ok(format!("{PREFIX}{hint}"))
        }
    }
}

fn render_validation(
    contract: &Contract,
    schema: &Schema,
    expression: &str,
    indent: &str,
    output: &mut String,
) -> Result<(), String> {
    match schema {
        Schema::Reference(_) | Schema::Object(_) | Schema::OneOf(_) | Schema::AllOf(_) => {}
        Schema::String(rules) => render_string_validation(expression, rules, indent, output),
        Schema::StringConstant(value) => {
            writeln!(
                output,
                "{indent}guard {expression} == {} else {{ throw GPContractError.constraint(\"unexpected constant for {expression}\") }}",
                quoted(value)
            )
            .unwrap();
        }
        Schema::Integer(rules) => render_integer_validation(expression, rules, indent, output),
        Schema::Boolean | Schema::Null => {}
        Schema::Nullable(inner) if needs_inline_validation(inner) => {
            writeln!(output, "{indent}if let value = {expression} {{").unwrap();
            render_validation(contract, inner, "value", &format!("{indent}    "), output)?;
            writeln!(output, "{indent}}}").unwrap();
        }
        Schema::Nullable(_) => {}
        Schema::Array(rules) => {
            render_array_validation(contract, expression, rules, indent, output)?
        }
    }
    Ok(())
}

fn render_string_validation(
    expression: &str,
    rules: &StringRules,
    indent: &str,
    output: &mut String,
) {
    if rules.minimum_length.is_none()
        && rules.maximum_length.is_none()
        && rules.pattern.is_none()
        && rules.allowed_values.is_empty()
    {
        return;
    }
    writeln!(
        output,
        "{indent}try gpValidateString({expression}, minimum: {}, maximum: {}, pattern: {})",
        swift_optional_u64(rules.minimum_length),
        swift_optional_u64(rules.maximum_length),
        rules
            .pattern
            .as_deref()
            .map(quoted)
            .unwrap_or_else(|| "nil".to_string())
    )
    .unwrap();
    if !rules.allowed_values.is_empty() {
        let values = rules
            .allowed_values
            .iter()
            .map(|value| quoted(value))
            .collect::<Vec<_>>()
            .join(", ");
        writeln!(
            output,
            "{indent}guard [{values}].contains({expression}) else {{ throw GPContractError.constraint(\"string is not an allowed enum value\") }}"
        )
        .unwrap();
    }
}

fn render_integer_validation(
    expression: &str,
    rules: &IntegerRules,
    indent: &str,
    output: &mut String,
) {
    if rules.minimum.is_none() && rules.maximum.is_none() {
        return;
    }
    writeln!(
        output,
        "{indent}try gpValidateInteger({expression}, minimum: {}, maximum: {})",
        swift_optional_i64(rules.minimum),
        swift_optional_i64(rules.maximum)
    )
    .unwrap();
}

fn render_array_validation(
    contract: &Contract,
    expression: &str,
    rules: &ArrayRules,
    indent: &str,
    output: &mut String,
) -> Result<(), String> {
    if let Some(minimum) = rules.minimum_items {
        writeln!(
            output,
            "{indent}guard {expression}.count >= {minimum} else {{ throw GPContractError.constraint(\"array is shorter than minItems\") }}"
        )
        .unwrap();
    }
    if let Some(maximum) = rules.maximum_items {
        writeln!(
            output,
            "{indent}guard {expression}.count <= {maximum} else {{ throw GPContractError.constraint(\"array is longer than maxItems\") }}"
        )
        .unwrap();
    }
    if rules.unique_items {
        writeln!(output, "{indent}try gpValidateUnique({expression})").unwrap();
    }
    if needs_inline_validation(&rules.items) {
        writeln!(output, "{indent}for item in {expression} {{").unwrap();
        render_validation(
            contract,
            &rules.items,
            "item",
            &format!("{indent}    "),
            output,
        )?;
        writeln!(output, "{indent}}}").unwrap();
    }
    Ok(())
}

fn needs_inline_validation(schema: &Schema) -> bool {
    match schema {
        Schema::String(rules) => {
            rules.minimum_length.is_some()
                || rules.maximum_length.is_some()
                || rules.pattern.is_some()
                || !rules.allowed_values.is_empty()
        }
        Schema::StringConstant(_) => true,
        Schema::Integer(rules) => rules.minimum.is_some() || rules.maximum.is_some(),
        Schema::Array(rules) => {
            rules.minimum_items.is_some()
                || rules.maximum_items.is_some()
                || rules.unique_items
                || needs_inline_validation(&rules.items)
        }
        Schema::Nullable(inner) => needs_inline_validation(inner),
        _ => false,
    }
}

fn quoted(value: &str) -> String {
    serde_json::to_string(value).expect("serializing a string cannot fail")
}

fn swift_optional_u64(value: Option<u64>) -> String {
    value
        .map(|value| value.to_string())
        .unwrap_or_else(|| "nil".to_string())
}

fn swift_optional_i64(value: Option<i64>) -> String {
    value
        .map(|value| value.to_string())
        .unwrap_or_else(|| "nil".to_string())
}

const SWIFT_PRELUDE: &str = r#"
import Foundation

public enum GPContractError: Error, Equatable, Sendable {
    case constraint(String)
    case unsupportedVariant(field: String, value: String)
}

public struct GPNull: Codable, Equatable, Hashable, Sendable {
    public init() {}

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        guard container.decodeNil() else {
            throw GPContractError.constraint("expected null")
        }
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encodeNil()
    }
}

private struct GPDynamicCodingKey: CodingKey {
    let stringValue: String
    let intValue: Int?

    init?(stringValue: String) {
        self.stringValue = stringValue
        intValue = nil
    }

    init?(intValue: Int) {
        stringValue = String(intValue)
        self.intValue = intValue
    }
}

private func gpValidateString(
    _ value: String,
    minimum: UInt64?,
    maximum: UInt64?,
    pattern: String?
) throws {
    let length = UInt64(value.unicodeScalars.count)
    if let minimum, length < minimum {
        throw GPContractError.constraint("string is shorter than minLength")
    }
    if let maximum, length > maximum {
        throw GPContractError.constraint("string is longer than maxLength")
    }
    if let pattern, value.range(of: pattern, options: .regularExpression) == nil {
        throw GPContractError.constraint("string does not match pattern")
    }
}

private func gpValidateInteger(
    _ value: Int64,
    minimum: Int64?,
    maximum: Int64?
) throws {
    if let minimum, value < minimum {
        throw GPContractError.constraint("integer is below minimum")
    }
    if let maximum, value > maximum {
        throw GPContractError.constraint("integer is above maximum")
    }
}

private func gpValidateUnique<T: Encodable>(_ values: [T]) throws {
    let encoder = JSONEncoder()
    encoder.outputFormatting = [.sortedKeys]
    let fingerprints = try values.map { try encoder.encode($0) }
    guard Set(fingerprints).count == fingerprints.count else {
        throw GPContractError.constraint("array items are not unique")
    }
}

"#;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn max_items_alone_requires_inline_validation() {
        let schema = Schema::Nullable(Box::new(Schema::Array(ArrayRules {
            items: Box::new(Schema::String(StringRules::default())),
            minimum_items: None,
            maximum_items: Some(3),
            unique_items: false,
        })));
        assert!(needs_inline_validation(&schema));
    }
}
