"""Regression tests for the first-party mobile contract integration wrapper."""

from __future__ import annotations

import tempfile
import unittest
from pathlib import Path
from unittest import mock

from tooling import mobile_contracts


class MobileContractIntegrationTests(unittest.TestCase):
    def test_discovers_homebrew_kotlin_when_it_is_not_on_path(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            kotlin_home = Path(temporary) / "kotlin" / "libexec"
            compiler = kotlin_home / "lib" / "kotlin-compiler.jar"
            compiler.parent.mkdir(parents=True)
            compiler.write_bytes(b"synthetic compiler marker")

            with (
                mock.patch.object(
                    mobile_contracts, "STANDARD_KOTLIN_HOMES", (kotlin_home,)
                ),
                mock.patch.object(mobile_contracts.glob, "glob", return_value=[]),
                mock.patch.object(mobile_contracts.shutil, "which", return_value=None),
            ):
                discovered = mobile_contracts.discover_kotlin_home(None)

            self.assertEqual(discovered, kotlin_home.resolve())

    def test_reproducibility_header_contains_only_stable_metadata(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            output = Path(temporary) / "Generated.swift"
            output.write_text(
                "// Generated by gp_contract_gen. Do not edit.\n"
                "// Canonical source: Synthetic\n\n"
                "import Foundation\n",
                encoding="utf-8",
            )

            mobile_contracts.add_reproducibility_header(output)

            source = output.read_text(encoding="utf-8")
            self.assertIn("// Generated by gp_contract_gen 0.1.0.", source)
            self.assertIn("// Protocol major: 1", source)
            self.assertIn("// Canonical source SHA-256: ", source)
            self.assertNotIn(str(mobile_contracts.REPOSITORY), source)

    def test_check_detects_drift_without_modifying_outputs(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            directory = Path(temporary)
            generated = {
                "swift": directory / "new.swift",
                "kotlin": directory / "new.kt",
            }
            committed = {
                "swift": directory / "committed.swift",
                "kotlin": directory / "committed.kt",
            }
            for path in generated.values():
                path.write_bytes(b"matching\n")
            for path in committed.values():
                path.write_bytes(b"matching\n")

            with (
                mock.patch.object(mobile_contracts, "COMMITTED_OUTPUTS", committed),
                mock.patch.object(mobile_contracts, "REPOSITORY", directory),
            ):
                mobile_contracts.compare_committed(generated)
                committed["kotlin"].write_bytes(b"stale\n")
                before = committed["kotlin"].read_bytes()
                with self.assertRaisesRegex(RuntimeError, "stale"):
                    mobile_contracts.compare_committed(generated)
                self.assertEqual(committed["kotlin"].read_bytes(), before)

    def test_generate_replaces_both_outputs(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            directory = Path(temporary)
            generated = {
                "swift": directory / "new.swift",
                "kotlin": directory / "new.kt",
            }
            committed = {
                "swift": directory / "swift" / "committed.swift",
                "kotlin": directory / "kotlin" / "committed.kt",
            }
            generated["swift"].write_bytes(b"swift\n")
            generated["kotlin"].write_bytes(b"kotlin\n")

            with mock.patch.object(mobile_contracts, "COMMITTED_OUTPUTS", committed):
                mobile_contracts.replace_committed(generated)

            self.assertEqual(committed["swift"].read_bytes(), b"swift\n")
            self.assertEqual(committed["kotlin"].read_bytes(), b"kotlin\n")
            self.assertEqual(
                [path for path in directory.rglob(".*") if path.is_file()], []
            )

    def test_generate_rolls_back_when_second_replace_fails(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            directory = Path(temporary)
            generated = {
                "swift": directory / "new.swift",
                "kotlin": directory / "new.kt",
            }
            committed = {
                "swift": directory / "swift" / "committed.swift",
                "kotlin": directory / "kotlin" / "committed.kt",
            }
            generated["swift"].write_bytes(b"new swift\n")
            generated["kotlin"].write_bytes(b"new kotlin\n")
            for path, content in (
                (committed["swift"], b"old swift\n"),
                (committed["kotlin"], b"old kotlin\n"),
            ):
                path.parent.mkdir(parents=True)
                path.write_bytes(content)

            real_replace = mobile_contracts.os.replace
            replace_calls = 0

            def fail_second_replace(source: Path, destination: Path) -> None:
                nonlocal replace_calls
                replace_calls += 1
                if replace_calls == 2:
                    raise OSError("synthetic second replacement failure")
                real_replace(source, destination)

            with (
                mock.patch.object(mobile_contracts, "COMMITTED_OUTPUTS", committed),
                mock.patch.object(
                    mobile_contracts.os,
                    "replace",
                    side_effect=fail_second_replace,
                ),
                self.assertRaisesRegex(OSError, "synthetic second replacement failure"),
            ):
                mobile_contracts.replace_committed(generated)

            self.assertEqual(committed["swift"].read_bytes(), b"old swift\n")
            self.assertEqual(committed["kotlin"].read_bytes(), b"old kotlin\n")
            self.assertEqual(
                [path for path in directory.rglob(".*") if path.is_file()], []
            )

    def test_generate_preserves_backup_when_rollback_fails(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            directory = Path(temporary)
            generated = {
                "swift": directory / "new.swift",
                "kotlin": directory / "new.kt",
            }
            committed = {
                "swift": directory / "swift" / "committed.swift",
                "kotlin": directory / "kotlin" / "committed.kt",
            }
            generated["swift"].write_bytes(b"new swift\n")
            generated["kotlin"].write_bytes(b"new kotlin\n")
            for path, content in (
                (committed["swift"], b"old swift\n"),
                (committed["kotlin"], b"old kotlin\n"),
            ):
                path.parent.mkdir(parents=True)
                path.write_bytes(content)

            real_replace = mobile_contracts.os.replace
            replace_calls = 0

            def fail_second_replace_and_rollback(
                source: Path, destination: Path
            ) -> None:
                nonlocal replace_calls
                replace_calls += 1
                if replace_calls in (2, 3):
                    raise OSError(f"synthetic replacement failure {replace_calls}")
                real_replace(source, destination)

            with (
                mock.patch.object(mobile_contracts, "COMMITTED_OUTPUTS", committed),
                mock.patch.object(
                    mobile_contracts.os,
                    "replace",
                    side_effect=fail_second_replace_and_rollback,
                ),
                self.assertRaisesRegex(RuntimeError, "rollback was incomplete") as error,
            ):
                mobile_contracts.replace_committed(generated)

            backups = list(
                committed["swift"].parent.glob(".committed.swift.backup.*")
            )
            self.assertEqual(committed["swift"].read_bytes(), b"new swift\n")
            self.assertEqual(committed["kotlin"].read_bytes(), b"old kotlin\n")
            self.assertEqual(len(backups), 1)
            self.assertEqual(backups[0].read_bytes(), b"old swift\n")
            self.assertIn(str(backups[0]), str(error.exception))

    def test_exact_toolchain_version_parsing(self) -> None:
        swift = "swift-driver version: 1.0 Apple Swift version 6.3.3"
        kotlin = "info: kotlinc-jvm 2.4.10 (JRE 21)"
        mobile_contracts.verify_expected_versions(swift, kotlin, "6.3.3", "2.4.10")
        with self.assertRaisesRegex(RuntimeError, "expected kotlinc-jvm"):
            mobile_contracts.verify_expected_versions(swift, kotlin, "6.3.3", "2.3.10")


if __name__ == "__main__":
    unittest.main()
